package idrcore;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : IDRCore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("IDRCore") 
public class HY_RECT_S extends StructObject {
	public HY_RECT_S() {
		super();
	}
	@CLong 
	@Field(0) 
	public long lLeft() {
		return this.io.getCLongField(this, 0);
	}
	@CLong 
	@Field(0) 
	public HY_RECT_S lLeft(long lLeft) {
		this.io.setCLongField(this, 0, lLeft);
		return this;
	}
	@CLong 
	@Field(1) 
	public long lRight() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public HY_RECT_S lRight(long lRight) {
		this.io.setCLongField(this, 1, lRight);
		return this;
	}
	@CLong 
	@Field(2) 
	public long lTop() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public HY_RECT_S lTop(long lTop) {
		this.io.setCLongField(this, 2, lTop);
		return this;
	}
	@CLong 
	@Field(3) 
	public long lBottom() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public HY_RECT_S lBottom(long lBottom) {
		this.io.setCLongField(this, 3, lBottom);
		return this;
	}
	public HY_RECT_S(Pointer pointer) {
		super(pointer);
	}
}
