package idrcore;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : IDRCore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("IDRCore") 
public class JL_ITEM extends StructObject {
	public JL_ITEM() {
		super();
	}
	/// C type : char[256]
	@Array({256}) 
	@Field(0) 
	public Pointer<Byte > pzTxt() {
		return this.io.getPointerField(this, 0);
	}
	@CLong 
	@Field(1) 
	public long left() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public JL_ITEM left(long left) {
		this.io.setCLongField(this, 1, left);
		return this;
	}
	@CLong 
	@Field(2) 
	public long top() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public JL_ITEM top(long top) {
		this.io.setCLongField(this, 2, top);
		return this;
	}
	@CLong 
	@Field(3) 
	public long right() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public JL_ITEM right(long right) {
		this.io.setCLongField(this, 3, right);
		return this;
	}
	@CLong 
	@Field(4) 
	public long bottom() {
		return this.io.getCLongField(this, 4);
	}
	@CLong 
	@Field(4) 
	public JL_ITEM bottom(long bottom) {
		this.io.setCLongField(this, 4, bottom);
		return this;
	}
	public JL_ITEM(Pointer pointer) {
		super(pointer);
	}
}
