package idrcore;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : IDRCore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("IDRCore") 
public class TERMB_ITEM extends StructObject {
	public TERMB_ITEM() {
		super();
	}
	/// C type : char[70][128]
	@Array({70, 128}) 
	@Field(0) 
	public Pointer<Byte > pzTxt() {
		return this.io.getPointerField(this, 0);
	}
	public TERMB_ITEM(Pointer pointer) {
		super(pointer);
	}
}
