package synpublic;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : SynPublic.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("SynIDCardAPI") 
public class IDCardData extends StructObject {
	public IDCardData() {
		super();
	}
	/**
	 * \u59d3\u540d<br>
	 * C type : char[32]
	 */
	@Array({32}) 
	@Field(0) 
	public Pointer<Byte> Name() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6027\u522b<br>
	 * C type : char[6]
	 */
	@Array({6}) 
	@Field(1) 
	public Pointer<Byte> Sex() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u540d\u65cf<br>
	 * C type : char[20]
	 */
	@Array({20}) 
	@Field(2) 
	public Pointer<Byte> Nation() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u51fa\u751f\u65e5\u671f<br>
	 * C type : char[18]
	 */
	@Array({18}) 
	@Field(3) 
	public Pointer<Byte> Born() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u4f4f\u5740<br>
	 * C type : char[72]
	 */
	@Array({72}) 
	@Field(4) 
	public Pointer<Byte> Address() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u8eab\u4efd\u8bc1\u53f7<br>
	 * C type : char[38]
	 */
	@Array({38}) 
	@Field(5) 
	public Pointer<Byte> IDCardNo() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u53d1\u8bc1\u673a\u5173<br>
	 * C type : char[32]
	 */
	@Array({32}) 
	@Field(6) 
	public Pointer<Byte> GrantDept() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \u6709\u6548\u5f00\u59cb\u65e5\u671f<br>
	 * C type : char[18]
	 */
	@Array({18}) 
	@Field(7) 
	public Pointer<Byte> UserLifeBegin() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u6709\u6548\u622a\u6b62\u65e5\u671f<br>
	 * C type : char[18]
	 */
	@Array({18}) 
	@Field(8) 
	public Pointer<Byte> UserLifeEnd() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[38]
	 */
	@Array({38}) 
	@Field(9) 
	public Pointer<Byte> reserved() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \u7167\u7247\u8def\u5f84<br>
	 * C type : char[255]
	 */
	@Array({255}) 
	@Field(10) 
	public Pointer<Byte> PhotoFileName() {
		return this.io.getPointerField(this, 10);
	}
	public IDCardData(Pointer pointer) {
		super(pointer);
	}
}
